#! /usr/bin/env python

from sesame.cli import entrypoint


def main():
    '''
    The main entry point for sesame CLI
    '''
    entrypoint()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nExiting gracefully on Ctrl-c')
